### ISSUE TITLE
Dependency hell on 0.5.0

### ISSUE THREAD

**Issue by twisted-pear** [tablet-mode/twod#8]
I'm writing a new ebuild for 0.5.0 and the dependencies have changed
* the readme and the setup.py file are no longer consistent
* requests 2.18.4 are now required, which is currently unstable on gentoo, does it work with 2.18.2 too?
* python-daemon 2.1.2 is not in gentoo at all right now, does 2.1.1 work? 1.6 is apparently not available for python 3 at all
* the `install_requires` contains configparser, however on python 3 there is no configparser (it's already builtin i think)
* the requirements in setup.py are fixed to a specific version, shouldn't it be `>= X`?
* is lockfile required or not? (the code suggests it is)

right now i'm patching setup.py thusly:
```
sed -e "s/'python-daemon==2.1.2'/'python-daemon>=2.1.1'/" -i setup.py
sed -e "s/'requests==2.18.4'/'requests>=2.18.2'/" -i setup.py
sed -e "/'configparser==3.5.0',/d" -i setup.py
```

thoughts?

**Comment by twisted-pear** [comment]
Update: I'm running twod-0.5.0 now with requests-2.18.2 and python-daemon-2.1.1 on python 3.5 and it does what it's supposed to do

**Comment by t4k1t** [comment]
Pushed 3a9422b to master which adresses the issues you put forth as follows:

> the readme and the setup.py file are no longer consistent

Removed dependencies from readme since they can be found in setup.py anyway

> requests 2.18.4 are now required, which is currently unstable on gentoo, does it work with 2.18.2 too?

Changed dependency to >=2.8.1, I didn't try to run twod with any older version since that's the oldest version I could find on gentoo

> python-daemon 2.1.2 is not in Gentoo at all right now, does 2.1.1 work? 1.6 is apparently not available for python 3 at all

Fixed by changing requirement to >=2.1.1, thanks for testing

> the install_requires contains configparser, however on python 3 there is no configparser (it's already builtin i think)

This is a Gentoo-specific problem, installing configparser via pip works perfectly fine for python 2 and 3 and can be verified by running the tox tests - Fixed it anyway

> the requirements in setup.py are fixed to a specific version, shouldn't it be >= X?

Indeed it's frowned upon to pin dependencies to a specific version - Changed it

> is lockfile required or not? (the code suggests it is)

It's required, tbh I have no idea why I never put it in the setup.py

I'd appreciate if you could let me know if these changes fix your issues. If so I'll prepare a new release.

**Comment by twisted-pear** [comment]
thanks for taking a look, two things:
* you now allow python-daemon < 2 for python 2, don't do this to yourself, 2.1.1 is available for python 2 too
* only fix the configparser situation in setup.py if you are sure this won't break stuff for other people, if this is a gentoo specific breakage i'll fix it in the ebuild (which is easy now that you wrote the code for me)

i'll report back as soon as i tested the commit

**Comment by t4k1t** [comment]
I've pushed my current work on this for now. If you run into this issue again and are still interested in it, please reopen a new ticket.
